Repository Simul-IO/SimulIO, pull requests merged in 2020-07, with the labels that each got.

#21 Add graph topologies
  simulate
  simulio/graph.py
Labels: algorithms, enhancement

#22 Fix random limit is wrong in receive_eliminated_msg transition
  examples/automata/luby_mis.ioa
Labels: bug

#25 Optimize async simulator run time.
  simulio/simulator.py
Labels: enhancement, simulator
